### ISSUE TITLE
The log file is erased whenever the server is restarted

### ISSUE THREAD

**Issue by FernandoCesarS** [VeliovGroup/Meteor-logger-file#13]
Versions:
Meteor: 1.6.0.1
ostrio:logger@2.0.6
ostrio:loggerfile@2.0.4

Debian, problem on the server (only tested server side yet).

This doesn't seem to happen every-time. But if I stop and restart the meteor project, the log file gets erased. Is this the expected behavior?

**Comment by dr-dimitru** [comment]
Hello @FernandoCesarS ,

This is expected behavior. All logs will be removed as soon as your application rebuilds or you run `meteor reset`. To keep your logs persistent during development use an absolute path outside of your project folder, e.g. `/logs` directory. Make sure selected directory is writable by node/meteor's process owner.

**Comment by dr-dimitru** [comment]
@FernandoCesarS added this info to the [FAQ](https://github.com/VeliovGroup/Meteor-logger-file#faq). Thank you for contribution.

Feel free to reopen it in case if the issue is still persists on your end.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-logger-file)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/loggerfile)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made

**Comment by FernandoCesarS** [comment]
Thanks for your answer and updated the FAQ. I'm not an expert in Meteor, but running Meteor apps in production environment sometimes implies restarting a container in case of a crash. Deleting the log in that situation would make it more difficult to identify the problem.

**Comment by dr-dimitru** [comment]
@FernandoCesarS read [this docs](https://github.com/VeliovGroup/Meteor-Files/wiki/MeteorUp-(MUP)-Usage) where we explained how to create persistent storage on containers.

Let me know wdyt
